### PR TITLE
powershell on linux use pwsh instead of powershell

### PR DESCRIPTION
**Pull request by scorpionlion**

### CODE REVIEW

**Comment by scorpionlion** [comment]
rerun pipeline

**Comment by scorpionlion** [comment]
Can this be approved please?

**Comment by svanoort** [comment]
@gabloe Can you comment on this one please?

**Comment by darxriggs** [comment]
It looks like pull-request #55 also covers this topic.

**Comment by casz** [comment]
This does not consider Windows that may have pwsh installed

**Pull request closed without merging**
